# Classification Metrics

Classification metrics are used to evaluate classification models.

Examples:

* Logistic Regression
* Decision Trees
* Random Forest
* SVM
* Neural Networks

---

# Confusion Matrix

A confusion matrix is the foundation of most classification metrics.

| Actual / Predicted | Positive | Negative |
| ------------------ | -------- | -------- |
| Positive           | TP       | FN       |
| Negative           | FP       | TN       |

Where:

* TP → True Positive
* TN → True Negative
* FP → False Positive
* FN → False Negative

---

# 1. Accuracy

Measures overall correctness of the model.

## Formula

[
Accuracy = \frac{TP + TN}{TP + TN + FP + FN}
]

## Use Case

* Balanced datasets

## Problem

Not reliable for imbalanced datasets.

Example:

* 95% normal cases
* 5% fraud cases

A model predicting everything as normal gets 95% accuracy but is useless.

---

# 2. Precision

Measures how many predicted positives are actually positive.

## Formula

[
Precision = \frac{TP}{TP + FP}
]

## Focus

False Positives

## Important When

False positives are costly.

Examples:

* Spam detection
* Email filtering

---

# 3. Recall (Sensitivity)

Measures how many actual positives were correctly identified.

## Formula

[
Recall = \frac{TP}{TP + FN}
]

## Focus

False Negatives

## Important When

Missing positive cases is dangerous.

Examples:

* Cancer detection
* Fraud detection

---

# 4. F1 Score

Harmonic mean of Precision and Recall.

## Formula

[
F1 = 2 \times \frac{Precision \times Recall}{Precision + Recall}
]

## Use Case

* Imbalanced datasets
* Need balance between Precision and Recall

---

# 5. Specificity

Measures how well the model identifies negative cases.

## Formula

[
Specificity = \frac{TN}{TN + FP}
]

## Important In

Medical testing

---

# 6. ROC Curve

ROC = Receiver Operating Characteristic Curve

Shows:

* TPR vs FPR

Where:

* TPR = Recall
* FPR = False Positive Rate

---

# 7. ROC-AUC Score

AUC = Area Under Curve

## Range

* 1.0 → Perfect model
* 0.5 → Random guessing
* <0.5 → Bad model

## Use Case

Measures overall classification performance.

---

# 8. Log Loss (Cross Entropy Loss)

Measures prediction uncertainty.

## Formula

[
LogLoss = -\frac{1}{N}\sum[y\log(\hat{y}) + (1-y)\log(1-\hat{y})]
]

## Important For

* Logistic Regression
* Neural Networks

Lower value is better.

---

# Multi-Class Classification Metrics

Used when more than 2 classes exist.

Examples:

* Cat/Dog/Bird classification
* Digit recognition

Techniques:

* Macro Average
* Micro Average
* Weighted Average

---

# Accuracy vs Precision vs Recall

| Metric    | Focus                      | Best Use          |
| --------- | -------------------------- | ----------------- |
| Accuracy  | Overall correctness        | Balanced data     |
| Precision | FP reduction               | Spam detection    |
| Recall    | FN reduction               | Medical diagnosis |
| F1 Score  | Precision + Recall balance | Imbalanced data   |

---

# Important Interview Questions

## 1. Why accuracy fails on imbalanced data?

Because high accuracy may still ignore minority classes.

---

## 2. Precision vs Recall?

* Precision focuses on FP
* Recall focuses on FN

---

## 3. When use F1 Score?

When dataset is imbalanced and both Precision & Recall matter.

---

## 4. ROC-AUC vs Accuracy?

ROC-AUC evaluates classifier quality across thresholds.
Accuracy depends on one threshold.

---

# Python Example

```python
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

y_true = [1, 0, 1, 1, 0]
y_pred = [1, 0, 0, 1, 1]

print("Accuracy:", accuracy_score(y_true, y_pred))
print("Precision:", precision_score(y_true, y_pred))
print("Recall:", recall_score(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))
```

---

# Placement Important Metrics

Must know deeply:

* Accuracy
* Precision
* Recall
* F1 Score
* ROC-AUC
* Confusion Matrix

Especially for:

* AI/ML interviews
* Kaggle
* Production ML systems
* Deep learning classification tasks

---

# Recommended Learning Order

```text
Confusion Matrix
    ↓
Accuracy
    ↓
Precision & Recall
    ↓
F1 Score
    ↓
ROC Curve & ROC-AUC
    ↓
Log Loss
```

# Code implementation

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import sklearn.metrics

In [14]:
df = pd.read_csv(r'C:\Users\ipartzix\Downloads\heart.csv')

In [22]:
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   52    1   0       125   212    0  ...      0      1.0      2   2     3       0
1   53    1   0       140   203    1  ...      1      3.1      0   0     3       0
2   70    1   0       145   174    0  ...      1      2.6      0   0     3       0
3   61    1   0       148   203    0  ...      0      0.0      2   1     3       0
4   62    0   0       138   294    1  ...      0      1.9      1   3     2       0

[5 rows x 14 columns]

In [23]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test =train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [25]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [26]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

c:\Users\ipartzix\miniconda3\envs\AI-ML-Env\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [27]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8536585365853658
Accuracy of Decision Trees 0.9804878048780488

In [29]:
confusion_matrix(y_test,y_pred1)

array([[82, 23],
       [ 7, 93]])

In [30]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  82  23
1   7  93

In [31]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

     0    1
0  101    4
1    0  100

In [33]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [34]:
result.sample(10)

      Actual Label  Logistic Regression Prediction  Decision Tree Prediction
451              1                               1                         1
1                0                               0                         0
309              1                               1                         1
164              0                               0                         0
286              1                               1                         1
1004             1                               1                         1
829              0                               0                         0
943              1                               0                         1
65               0                               1                         0
818              1                               1                         1

In [35]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [36]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  82  23
1   7  93
--------------------------------------------------
Precision -  0.8017241379310345
Recall -  0.93
F1 score -  0.8611111111111112

In [ ]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision -  0.9615384615384616
Recall -  1.0
F1 score -  0.9803921568627451

In [38]:
precision_score(y_test,y_pred1,average=None)

array([0.92134831, 0.80172414])

In [ ]:
precision_score(y_test,y_pred2,average=None)

array([1.        , 0.96153846])

In [ ]:
recall_score(y_test,y_pred2,average=None)

array([0.96190476, 1.        ])

In [10]:
import os

print(os.listdir(r"D:\datasets\mnist_train.csv"))
df1 = pd.read_csv(r"D:\datasets\mnist_train.csv\mnist_train.csv")

['mnist_train.csv']

In [12]:
df1.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df1.iloc[:, 1:],
    df1.iloc[:, 0],
    test_size=0.2,
    random_state=2
)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [21]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [22]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

c:\Users\ipartzix\miniconda3\envs\AI-ML-Env\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [23]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9171666666666667
Accuracy of Decision Trees 0.87225

In [25]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

      0     1     2     3     4    5     6     7     8     9
0  1139     0     6     3     1   11    10     4     9     0
1     0  1306     8     3     6   10     2     5    12     2
2     8    14  1066    27    11    5    19    13    25     6
3     3     6    27  1126     2   34     3    10    29    12
4     3     4    12     2  1133    2    11     6     8    36
5    16    10    11    32     9  931    21     7    39     7
6     6     5    11     1    12   18  1110     1     5     0
7     4     3    14    10    12    2     0  1128     5    42
8     3    27    11    31     8   32     7     7  1031     9
9     3     2     4    15    43   10     0    32    17  1036

In [26]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

      0     1     2     3     4    5     6     7    8    9
0  1079     1    14    12     6   23    18     2   16   12
1     1  1284    13     8     5   13    11     5    6    8
2    12    10  1019    29    19    9    25    34   25   12
3     7     9    30  1074    12   51     5    10   32   22
4     6     6    16     9  1071   14    17     7   20   51
5    17    14     8    61     8  887    26     6   31   25
6    14     6    17     6    20   29  1054     4   13    6
7     7     7    22    11    22    5     1  1108   12   25
8    12    18    24    39    21   35    27    15  942   33
9    12     5     6    25    68   19     4    32   42  949

In [27]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [30]:
precision_score(y_test,y_pred1,average='weighted')

0.917022827062738

In [31]:
recall_score(y_test,y_pred1,average='weighted')

0.9171666666666667

In [32]:
f1_score(y_test,y_pred1,average='weighted')

0.9170485929607194

In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1183
           1       0.95      0.96      0.96      1354
           2       0.91      0.89      0.90      1194
           3       0.90      0.90      0.90      1252
           4       0.92      0.93      0.92      1217
           5       0.88      0.86      0.87      1083
           6       0.94      0.95      0.94      1169
           7       0.93      0.92      0.93      1220
           8       0.87      0.88      0.88      1166
           9       0.90      0.89      0.90      1162

    accuracy                           0.92     12000
   macro avg       0.92      0.92      0.92     12000
weighted avg       0.92      0.92      0.92     12000