
# Handling Date and Time Variables

In [79]:
import numpy as np
import pandas as pd

In [80]:
date = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/orders.csv")
time = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/messages.csv")

In [81]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [82]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [83]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [84]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

## Working with Dates

In [85]:

# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [86]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

#### 1.Extract Year

In [87]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
907 2019-08-13        5073       13       1       2019
443 2018-09-21         873       25      16       2018
471 2018-11-05        6430       13       1       2018
5   2018-08-23        1811       25       4       2018
181 2019-04-12        1744       13       2       2019

#### 2. Extract Month

In [88]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [89]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

#### Extract Days

In [90]:
date['date_month_no'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,10,December
1,2018-08-15,3646,14,157,2018,15,August
2,2018-10-23,1859,25,1,2018,23,October
3,2019-08-17,7292,25,1,2019,17,August
4,2019-01-06,4344,25,3,2019,6,January

#### Day of week

In [91]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,10,December,1
1,2018-08-15,3646,14,157,2018,15,August,2
2,2018-10-23,1859,25,1,2018,23,October,1
3,2019-08-17,7292,25,1,2019,17,August,5
4,2019-01-06,4344,25,3,2019,6,January,6

#### Day of week - name

In [92]:
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no date_month_name  date_dow date_dow_name
0 2019-12-10       2019             10        December         1       Tuesday
1 2018-08-15       2018             15          August         2     Wednesday
2 2018-10-23       2018             23         October         1       Tuesday
3 2019-08-17       2019             17          August         5      Saturday
4 2019-01-06       2019              6         January         6        Sunday

#### is weekend?

In [93]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,10,December,1,Tuesday,0
1,2018-08-15,2018,15,August,2,Wednesday,0
2,2018-10-23,2018,23,October,1,Tuesday,0
3,2019-08-17,2019,17,August,5,Saturday,1
4,2019-01-06,2019,6,January,6,Sunday,1

#### Extract week of the year

In [94]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,10,December,1,Tuesday,0,50
1,2018-08-15,2018,15,August,2,Wednesday,0,33
2,2018-10-23,2018,23,October,1,Tuesday,0,43
3,2019-08-17,2019,17,August,5,Saturday,1,33
4,2019-01-06,2019,6,January,6,Sunday,1,1

#### Extract Quarter

In [95]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,10,December,1,Tuesday,0,50,4
1,2018-08-15,2018,15,August,2,Wednesday,0,33,3
2,2018-10-23,2018,23,October,1,Tuesday,0,43,4
3,2019-08-17,2019,17,August,5,Saturday,1,33,3
4,2019-01-06,2019,6,January,6,Sunday,1,1,1

#### Extract Semester

In [96]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,10,December,1,Tuesday,0,50,4,2
1,2018-08-15,2018,15,August,2,Wednesday,0,33,3,2
2,2018-10-23,2018,23,October,1,Tuesday,0,43,4,2
3,2019-08-17,2019,17,August,5,Saturday,1,33,3,2
4,2019-01-06,2019,6,January,6,Sunday,1,1,1,1

#### Extract Time elapsed between dates

In [97]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 3, 22, 19, 56, 59, 65966)

In [98]:
today - date['date']

0     2294 days 19:56:59.065966
1     2776 days 19:56:59.065966
2     2707 days 19:56:59.065966
3     2409 days 19:56:59.065966
4     2632 days 19:56:59.065966
                 ...
995   2722 days 19:56:59.065966
996   2663 days 19:56:59.065966
997   2511 days 19:56:59.065966
998   2576 days 19:56:59.065966
999   2350 days 19:56:59.065966
Name: date, Length: 1000, dtype: timedelta64[us]

In [99]:
(today - date['date']).dt.days

0      2294
1      2776
2      2707
3      2409
4      2632
       ...
995    2722
996    2663
997    2511
998    2576
999    2350
Name: date, Length: 1000, dtype: int64

In [100]:
# Months passed

np.round((today - date['date']) / np.timedelta64(30, 'D'), 0)

0      76.0
1      93.0
2      90.0
3      80.0
4      88.0
       ...
995    91.0
996    89.0
997    84.0
998    86.0
999    78.0
Name: date, Length: 1000, dtype: float64

In [101]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [102]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [103]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [104]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [105]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

#### Extract Time part

In [106]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

#### Time difference

In [107]:
today - time['date']

0     4480 days 19:06:59.065966
1     4344 days 20:16:59.065966
2     4830 days 19:35:59.065966
3     4132 days 19:25:59.065966
4     4529 days 20:45:59.065966
                 ...
995   5119 days 19:06:59.065966
996   4440 days 20:42:59.065966
997   4905 days 20:19:59.065966
998   5021 days 20:22:59.065966
999   4293 days 20:31:59.065966
Name: date, Length: 1000, dtype: timedelta64[us]

In [108]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.871408e+08
1      3.753946e+08
2      4.173826e+08
3      3.570748e+08
4      3.913804e+08
           ...
995    4.423504e+08
996    3.836906e+08
997    4.238652e+08
998    4.338878e+08
999    3.709891e+08
Name: date, Length: 1000, dtype: float64

In [109]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.452347e+06
1      6.256577e+06
2      6.956376e+06
3      5.951246e+06
4      6.523006e+06
           ...
995    7.372507e+06
996    6.394843e+06
997    7.064420e+06
998    7.231463e+06
999    6.183152e+06
Name: date, Length: 1000, dtype: float64

In [110]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      107539.116407
1      104276.283074
2      115939.599741
3       99187.433074
4      108716.766407
           ...
995    122875.116407
996    106580.716407
997    117740.333074
998    120524.383074
999    103052.533074
Name: date, Length: 1000, dtype: float64