
# Handling Date and Time Variables

In [19]:
import numpy as np
import pandas as pd

In [20]:
date = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/orders.csv")
time = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/messages.csv")

In [21]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [22]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [23]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [24]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

## Working with Dates

In [25]:

# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [26]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

#### 1.Extract Year

In [27]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
711 2019-07-13        6201        0       3       2019
740 2019-08-05         709       16     220       2019
21  2018-08-19        1191       13      50       2018
817 2019-10-20        3271        0       1       2019
292 2018-09-02        1455        0       1       2018

#### 2. Extract Month

In [28]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [29]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

#### Extract Days

In [30]:
date['date_month_no'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,10,December
1,2018-08-15,3646,14,157,2018,15,August
2,2018-10-23,1859,25,1,2018,23,October
3,2019-08-17,7292,25,1,2019,17,August
4,2019-01-06,4344,25,3,2019,6,January

#### Day of week

In [31]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,10,December,1
1,2018-08-15,3646,14,157,2018,15,August,2
2,2018-10-23,1859,25,1,2018,23,October,1
3,2019-08-17,7292,25,1,2019,17,August,5
4,2019-01-06,4344,25,3,2019,6,January,6

#### Day of week - name

In [32]:
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no date_month_name  date_dow date_dow_name
0 2019-12-10       2019             10        December         1       Tuesday
1 2018-08-15       2018             15          August         2     Wednesday
2 2018-10-23       2018             23         October         1       Tuesday
3 2019-08-17       2019             17          August         5      Saturday
4 2019-01-06       2019              6         January         6        Sunday

#### is weekend?

In [33]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,10,December,1,Tuesday,0
1,2018-08-15,2018,15,August,2,Wednesday,0
2,2018-10-23,2018,23,October,1,Tuesday,0
3,2019-08-17,2019,17,August,5,Saturday,1
4,2019-01-06,2019,6,January,6,Sunday,1

#### Extract week of the year

In [36]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,10,December,1,Tuesday,0,50
1,2018-08-15,2018,15,August,2,Wednesday,0,33
2,2018-10-23,2018,23,October,1,Tuesday,0,43
3,2019-08-17,2019,17,August,5,Saturday,1,33
4,2019-01-06,2019,6,January,6,Sunday,1,1

#### Extract Quarter

In [37]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,10,December,1,Tuesday,0,50,4
1,2018-08-15,2018,15,August,2,Wednesday,0,33,3
2,2018-10-23,2018,23,October,1,Tuesday,0,43,4
3,2019-08-17,2019,17,August,5,Saturday,1,33,3
4,2019-01-06,2019,6,January,6,Sunday,1,1,1

#### Extract Semester

In [38]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,10,December,1,Tuesday,0,50,4,2
1,2018-08-15,2018,15,August,2,Wednesday,0,33,3,2
2,2018-10-23,2018,23,October,1,Tuesday,0,43,4,2
3,2019-08-17,2019,17,August,5,Saturday,1,33,3,2
4,2019-01-06,2019,6,January,6,Sunday,1,1,1,1

#### Extract Time elapsed between dates

In [39]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 3, 22, 19, 51, 4, 194862)

In [40]:
today - date['date']

0     2294 days 19:51:04.194862
1     2776 days 19:51:04.194862
2     2707 days 19:51:04.194862
3     2409 days 19:51:04.194862
4     2632 days 19:51:04.194862
                 ...
995   2722 days 19:51:04.194862
996   2663 days 19:51:04.194862
997   2511 days 19:51:04.194862
998   2576 days 19:51:04.194862
999   2350 days 19:51:04.194862
Name: date, Length: 1000, dtype: timedelta64[us]