# Sentiment Analysis

### Naive Bayes 
- Gaussian Naive Bayes (GaussianNB)
- Multinomial Naive Bayes (MultinomialNB)
- Bernoulli Naive Bayes (BernoulliNB)

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
df = pd.read_csv('/home/ipartzix/ML-dataset/IMDB Dataset.csv')

In [11]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [12]:
df.describe

<bound method NDFrame.describe of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]>

In [13]:
df ["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text data cleaning 
1. Sample 10000 rows 
2. Remove html tags 
3. Remove special characters 
4. Converting every thing to lower case 
5. Removing stop words 
6. Stamming

In [33]:
df= df.sample(10000)

In [15]:
df.info

<bound method DataFrame.info of                                                   review sentiment
49756  I just caught this on Showtime...ewwwwwww, not...  negative
21476  http://video.google.com/videoplay?docid=211772...  positive
9392   This one is a very solid Randolph Scott Wester...  positive
45988  To summarize this movie: Without a real plot, ...  negative
14081  I wouldn't go so far as to not recommend this ...  positive
...                                                  ...       ...
31251  This film is bad. Not so bad it is good. Just ...  negative
7457   Two days after seeing this thing, I'm still in...  negative
12840  I think it's time John Rambo move on with his ...  negative
1793   It was evident until the final credits that th...  positive
33453  La Coda Dello Scorpione (a.k.a. Case of the Sc...  positive

[10000 rows x 2 columns]>

In [16]:
# df['sentiment'].replace({"positive": 1 , "negative":0},inplace= True)  # it may automatic downcasting

df['sentiment'] = df['sentiment'].replace({
    "positive": 1,
    "negative": 0
})
# the second version is the recommended modern Pandas style.

/tmp/ipykernel_23321/928976059.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'] = df['sentiment'].replace({

In [17]:
df.head()

                                                  review  sentiment
49756  I just caught this on Showtime...ewwwwwww, not...          0
21476  http://video.google.com/videoplay?docid=211772...          1
9392   This one is a very solid Randolph Scott Wester...          1
45988  To summarize this movie: Without a real plot, ...          0
14081  I wouldn't go so far as to not recommend this ...          1

In [18]:
"""
Removing HTML tags from the review text using Regular Expressions (regex). The regex pattern '<.*?>' matches any substring that starts with '<', followed by any characters (non-greedy), and ends with '>'. This effectively captures HTML tags, which can then be removed from the text.

"""

import re # Regular Expression

clean  = re.compile('<.*?>')  # regex to remove html tags
re.sub(clean, '', df.iloc[2].review ) # "Take the review in the 3rd row, find all HTML tags, and replace them with nothing."

"This one is a very solid Randolph Scott Western. He plays Bat Masterson and goes to Liberal, Kansas to clean up the town. He becomes good friends with Robert Ryan who played a very, straight up leading man role. It was not until after this that Robert Ryan began playing much darker roles. In fact, in 1947 Randolph Scott made one other movie which was not a western and never made anything but westerns after that until he retired in 1962. This movie has good pacing and builds up to the climax steadily. I can't say any more as it would give away the plot. Be sure to see this one. 8/10"

In [19]:
# function to clean the review text by removing HTML tags 
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [20]:
df['review'] = df['review'].apply(clean_html)

In [21]:
# conver lower case
def convert_lower(text):
    return text.lower()

In [22]:
df['review'] = df['review'].apply(convert_lower)

In [23]:
# function to remove special characters from the review text using Regular Expressions (regex). The regex pattern '[^a-zA-Z0-9\s]' matches any character that is not a letter (uppercase or lowercase), a digit, or whitespace. This effectively captures special characters, which can then be removed from the text.
def remove_special_characters(text):
    x=''
    for i in text:
        if i.isalnum() or i.isspace():
            x+=i
        else:
            x+=' '

    return x

In [24]:
df['review'] = df['review'].apply(remove_special_characters)

In [25]:
# remove stop words from the review text using the Natural Language Toolkit (nltk). Stop words are common words that are often removed from text data to improve the performance of natural language processing models. The function takes a string of text as input, splits it into individual words, filters out any stop words, and then joins the remaining words back into a single string.
import nltk
from nltk.corpus import stopwords
def remove_stop_words(text):
    x=[]
    for i in text.split():
        if i in stopwords.words('english'):
            x.append(i)

    y=x[:]
    x.clear()
    return y

In [26]:
df['review'] = df['review'].apply(remove_special_characters)

In [27]:
df["review"] = df["review"].str.split()
df["review"].iloc[0]

['i',
 'just',
 'caught',
 'this',
 'on',
 'showtime',
 'ewwwwwww',
 'not',
 'even',
 'fun',
 'in',
 'a',
 'bad',
 'movie',
 'kind',
 'of',
 'way',
 'one',
 'of',
 'the',
 'lamest',
 'monster',
 'flicks',
 'i',
 've',
 'ever',
 'seen',
 'plus',
 'the',
 'tv',
 'reporter',
 'in',
 'the',
 'movie',
 'was',
 'that',
 'annoying',
 'jerri',
 'from',
 'a',
 'past',
 'season',
 'of',
 'survivor',
 'the',
 'only',
 'amusing',
 'thing',
 'was',
 'that',
 'the',
 'secret',
 'base',
 'was',
 'the',
 'house',
 'from',
 'fantasy',
 'island',
 'and',
 'a',
 'million',
 'other',
 'movies',
 'and',
 'tv',
 'shows',
 'the',
 'place',
 'is',
 'located',
 'in',
 'the',
 'l',
 'a',
 'area',
 'i',
 'fully',
 'expected',
 'mr',
 'roarke',
 'and',
 'tattoo',
 'to',
 'come',
 'out',
 'and',
 'greet',
 'the',
 'visitors',
 'if',
 'tattoo',
 'had',
 'gotten',
 'eaten',
 'by',
 'the',
 'snake',
 'i',
 'might',
 'have',
 'given',
 'this',
 'movie',
 'a',
 '2',
 'but',
 'oh',
 'well',
 'watching',
 'people',
 'stand',
 'there',
 'and',
 'scream',
 'for',
 'five',
 'minutes',
 'while',
 'the',
 'komodo',
 'or',
 'the',
 'cobra',
 'loomed',
 'over',
 'them',
 'instead',
 'of',
 'making',
 'a',
 'run',
 'for',
 'it',
 'was',
 'pretty',
 'funny',
 'especially',
 'because',
 'you',
 'could',
 'really',
 'tell',
 'that',
 'they',
 'were',
 'just',
 'screaming',
 'at',
 'an',
 'empty',
 'spot',
 'where',
 'the',
 'computer',
 'animators',
 'would',
 'later',
 'paint',
 'in',
 'the',
 'monster',
 'i',
 'nearly',
 'fell',
 'out',
 'of',
 'my',
 'chair',
 'though',
 'when',
 'in',
 'a',
 'flashback',
 'scene',
 'they',
 'brought',
 'in',
 'either',
 'the',
 'cobra',
 'or',
 'the',
 'komodo',
 'then',
 'normal',
 'size',
 'in',
 'some',
 'indestructible',
 'solid',
 'steel',
 'container',
 'with',
 'some',
 'air',
 'holes',
 'drilled',
 'into',
 'it',
 'wouldn',
 't',
 'a',
 'wire',
 'cage',
 'have',
 'sufficed',
 'lol',
 'guess',
 'they',
 'couldn',
 't',
 'afford',
 'to',
 'rent',
 'a',
 'real',
 'komodo',
 'and',
 'cobra',
 'i',
 'have',
 'to',
 'remember',
 'i',
 'rent',
 'showtime',
 'for',
 'their',
 'series',
 'and',
 'not',
 'their',
 'movies']

In [28]:
df.head()

                                                  review  sentiment
49756  [i, just, caught, this, on, showtime, ewwwwwww...          0
21476  [http, video, google, com, videoplay, docid, 2...          1
9392   [this, one, is, a, very, solid, randolph, scot...          1
45988  [to, summarize, this, movie, without, a, real,...          0
14081  [i, wouldn, t, go, so, far, as, to, not, recom...          1

In [29]:
# Performing sentiment analysis on the cleaned review text using the TextBlob library. The function takes a string of text as input, creates a TextBlob object, and then calculates the sentiment polarity of the text. The polarity score ranges from -1 (negative sentiment) to 1 (positive sentiment), with 0 indicating neutral sentiment. The function returns the polarity score as a float.
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [30]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z= y[:]
    y.clear()
    return z

In [31]:
stem_words(["I","loved", "loving","it"])

['i', 'love', 'love', 'it']

In [34]:
df['review'] = df['review'].apply(stem_words)

In [35]:
# join back
def join_back(text):
    return ' '.join(text)

In [36]:
df['review'] = df['review'].apply(join_back)

In [37]:
df.review.head()

5008     what alic found wa a pleasant discoveri as wri...
5440     the biggest hero is one of the greatest movi e...
36684    although i total agre with the previou comment...
20706    worst movi ever what wa the purpos of film thi...
42761    the falcon and the snowman is base on a true s...
Name: review, dtype: object

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [39]:
X=cv.fit_transform(df['review']).toarray()

In [40]:
X.shape

(10000, 36659)

In [41]:
y = df.iloc[:, -1].values

In [42]:
y.shape

(10000,)

In [43]:
y

array([0, 1, 1, ..., 1, 1, 0], shape=(10000,))

In [ ]:
# Split the dataset into training and testing sets using sklearn's train_test_split function.
# The test size is set to 20% of the dataset, and a random state is provided for reproducibility.
from sklearn.model_selection import train_test_split

In [ ]:
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 1), (2000, 1), (8000,), (2000,))

In [ ]:
from sklearn.naive_bayes import GaussianNB ,MultinomialNB, BernoulliNB

In [ ]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [ ]:
clf1.fit(X_train , y_train)

GaussianNB()

In [ ]:
clf2.fit(X_train , y_train)

/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:302: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  self.y_type_ = type_of_target(y, input_name="y")
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/utils/multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:359: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_is_multilabel = type_of_target(y).startswith("multilabel")
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:528: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y)

MultinomialNB()

In [ ]:
clf3.fit(X_train , y_train)

/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:302: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  self.y_type_ = type_of_target(y, input_name="y")
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/utils/multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:359: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_is_multilabel = type_of_target(y).startswith("multilabel")
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:528: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y)

BernoulliNB()