# Sentiment Analysis

### Naive Bayes 
- Gaussian Naive Bayes (GaussianNB)
- Multinomial Naive Bayes (MultinomialNB)
- Bernoulli Naive Bayes (BernoulliNB)

In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [76]:
df = pd.read_csv('/home/ipartzix/ML-dataset/IMDB Dataset.csv')

In [77]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [78]:
df.describe

<bound method NDFrame.describe of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]>

In [79]:
df ["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text data cleaning 
1. Sample 10000 rows 
2. Remove html tags 
3. Remove special characters 
4. Converting every thing to lower case 
5. Removing stop words 
6. Stamming

In [80]:
df= df.sample(10000)

In [81]:
df.info

<bound method DataFrame.info of                                                   review sentiment
25648  Back when Alec Baldwin and Kim Basinger were a...  negative
6180   Camp with a capital C. Think of Mask and the A...  positive
21490  David and Bathsheba is a lavish Hollywood Bibl...  positive
15449  Meaning: if this movie got pitched, scripted, ...  negative
22069  i'm ask... what a f*** are whit the real-TV ne...  negative
...                                                  ...       ...
29135  Not too long ago I bought a cheap VHS tape ent...  negative
49467  Some said that this was a nose candy glorifica...  positive
5856   I've seen The Blob several times and is one of...  positive
33092  Finally, after years of awaiting a new film to...  positive
44526  "The Twins Effect" is the worst movie I've see...  negative

[10000 rows x 2 columns]>

In [82]:
# df['sentiment'].replace({"positive": 1 , "negative":0},inplace= True)  # it may automatic downcasting

df['sentiment'] = df['sentiment'].replace({
    "positive": 1,
    "negative": 0
})
# the second version is the recommended modern Pandas style.

/tmp/ipykernel_6835/928976059.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'] = df['sentiment'].replace({

In [83]:
df.head()

                                                  review  sentiment
25648  Back when Alec Baldwin and Kim Basinger were a...          0
6180   Camp with a capital C. Think of Mask and the A...          1
21490  David and Bathsheba is a lavish Hollywood Bibl...          1
15449  Meaning: if this movie got pitched, scripted, ...          0
22069  i'm ask... what a f*** are whit the real-TV ne...          0

In [84]:
"""
Removing HTML tags from the review text using Regular Expressions (regex). The regex pattern '<.*?>' matches any substring that starts with '<', followed by any characters (non-greedy), and ends with '>'. This effectively captures HTML tags, which can then be removed from the text.

"""

import re # Regular Expression

clean  = re.compile('<.*?>')  # regex to remove html tags
re.sub(clean, '', df.iloc[2].review ) # "Take the review in the 3rd row, find all HTML tags, and replace them with nothing."

"David and Bathsheba is a lavish Hollywood Biblical picture produced out of 20th Century Fox by Darryl F. Zanuck, directed by Henry King and starring Gregory Peck {King David}, Susan Hayward (Bathsheba), Raymond Massey (Nathan), Kieron Moore (Uriah) and Jayne Meadows (Michal).The film is based around the second Old Testament book of Samuel from the Holy Bible. It follows King David, who as a child had slain the giant Goliath, and now we find him in adulthood as the second King of Israel. A tough and assured King, David however has affairs of the heart causing great problems. For once he spies Bathsheba taking a shower {re;bath}, it 's the start of a journey encompassing adultery and betrayal; a journey that will end in the judgement of God being called upon.Typically for the genre, David & Bathsheba is a large, grandiose production. From its excellent set designs to it's positively gorgeous Technicolor photography {Leon Shamroy}, it has enough quality to warrant sitting along side the best the genre has to offer as regards production values. Untypically, tho, the film is sedately paced and relies on 99% of its worth being driven purely by dialogue. This is not one for action fans or anyone who needs some swash to go with their buckle. This is a very humanist picture, in fact lets not beat around the burning bush here, it's a Biblical love story flecked with sins of the heart. But that is no bad thing at all, because breaking it down we find it's very well acted {Peck has a stoic yet vulnerable thing going on real well & Hayward is pushing it to the max}, and it be a fine story directed with knowing skill by the often forgotten Henry King. And although some of the dialogue is admittedly cringe inducing, the character flow is never interrupted as Phillip Dunne's (The Ghost and Mrs. Muir) Oscar nominated screenplay holds the attention throughout.Sometimes a forgotten picture in terms of the Biblical/Swords & Sandals genres (most likely because it is a talky piece that has heart as its main selling point), but really it's well worth the time of anyone interested in the most lavish of genres. 7/10"

In [85]:
X = df["sentiment"]
y = df["review"]

In [86]:
X = X.values.reshape(-1, 1)

In [87]:
# Split the dataset into training and testing sets using sklearn's train_test_split function.
# The test size is set to 20% of the dataset, and a random state is provided for reproducibility.
from sklearn.model_selection import train_test_split

In [88]:
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [89]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 1), (2000, 1), (8000,), (2000,))

In [90]:
from sklearn.naive_bayes import GaussianNB ,MultinomialNB, BernoulliNB

In [91]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [92]:
clf1.fit(X_train , y_train)

GaussianNB()

In [93]:
clf2.fit(X_train , y_train)

/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:302: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  self.y_type_ = type_of_target(y, input_name="y")
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/utils/multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:359: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_is_multilabel = type_of_target(y).startswith("multilabel")
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:528: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y)

MultinomialNB()

In [94]:
clf3.fit(X_train , y_train)

/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:302: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  self.y_type_ = type_of_target(y, input_name="y")
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/utils/multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:359: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_is_multilabel = type_of_target(y).startswith("multilabel")
/home/ipartzix/miniconda3/envs/AI-ML-Env/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:528: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y)

BernoulliNB()