# Sentiment Analysis

### Naive Bayes 
- Gaussian Naive Bayes (GaussianNB)
- Multinomial Naive Bayes (MultinomialNB)
- Bernoulli Naive Bayes (BernoulliNB)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/kaggle/input/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.describe

<bound method NDFrame.describe of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]>

In [5]:
df ["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text data cleaning 
1. Sample 10000 rows 
2. Remove html tags 
3. Remove special characters 
4. Converting every thing to lower case 
5. Removing stop words 
6. Stamming

In [6]:
df= df.sample(10000)

In [7]:
df.info

<bound method DataFrame.info of                                                   review sentiment
21925  The 60s (1999) D: Mark Piznarski. Josh Hamilto...  negative
41703  This sleek, sexy movie is a must-see. Only upo...  negative
41531  If you're looking for an original horror flick...  positive
32676  Okul is the first of its kind in Turkish cinem...  positive
45498  Sur mes lèvres or READ MY LIPS is fine little ...  positive
...                                                  ...       ...
24390  To be fair, I couldn't bear to watch this movi...  negative
30993  <br /><br />In the process of boring you with ...  negative
34567  Most definitely the worst Columbo ever dreamt ...  negative
13924  **1/2 Elisha Cuthbert, Chad Michael Murray, Br...  positive
24313  If Fassbinder has made a worse film, I sure do...  negative

[10000 rows x 2 columns]>

In [8]:
# df['sentiment'].replace({"positive": 1 , "negative":0},inplace= True)  # it may automatic downcasting

df['sentiment'] = df['sentiment'].replace({
    "positive": 1,
    "negative": 0
})
# the second version is the recommended modern Pandas style.

/tmp/ipykernel_16/928976059.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'] = df['sentiment'].replace({

In [9]:
df.head()

                                                  review  sentiment
21925  The 60s (1999) D: Mark Piznarski. Josh Hamilto...          0
41703  This sleek, sexy movie is a must-see. Only upo...          0
41531  If you're looking for an original horror flick...          1
32676  Okul is the first of its kind in Turkish cinem...          1
45498  Sur mes lèvres or READ MY LIPS is fine little ...          1

In [10]:
"""
Removing HTML tags from the review text using Regular Expressions (regex). The regex pattern '<.*?>' matches any substring that starts with '<', followed by any characters (non-greedy), and ends with '>'. This effectively captures HTML tags, which can then be removed from the text.

"""

import re # Regular Expression

clean  = re.compile('<.*?>')  # regex to remove html tags
re.sub(clean, '', df.iloc[2].review ) # "Take the review in the 3rd row, find all HTML tags, and replace them with nothing."

'If you\'re looking for an original horror flick, this might be the one for you. It\'s strange and at times lingers on stupidity, but it\'s just such a good looking, nice sounding and original movie, it never fails, except maybe during the over long climax. "Nightbreed" is a must see for horror fans, or for fans of monster movie make-up.Boone (Craig Sheffer) has been having dreams of a town called Midian full of mutant creatures. In therapy, his psychiatrist Dr. Decker (horror director David Cronenberg) has come to the conclusion that Boone is a murderer, and gives him hallucinogenic pills, and tells him to turn himself in. After almost getting killed, Boone ends up at the hospital, where he runs into a mental patient who also knows about Midian, and tells Boone where to go. Midian, located in a graveyard, is inhabited by vile mutant creatures that don\'t let Boone in. After escaping with only a nasty bite, Boone is shot dead by the police, who were lead to his location by Dr. Decker. But Boone isn\'t dead. The bite causes him to live, and he goes off to Midian. Meanwhile, Boone\'s girlfriend Lori (Anne Bobby) tries to find Boone and get to the bottom of this. When Dr. Decker also finds out about this place, chaos ensues.The plot seems long and complicated, but it really isn\'t hard to understand. The plot, among other things, makes this movie really interesting. The make-up effects are astounding. The creatures look unique and amazing, and make this a very appealing film. To add to more senses appeal, we have a musical score by Danny Elfman, that is both lush and bouncy, and fits the film like a glove. The shots in the movie are also set up beautifully. The cinematography is lovely, and the movie sets up an atmosphere that is never broken. Even the acting is good, with the biggest surprise being director David Cronenberg giving a great, menacing performance as the man, who for one reason or another, wants to see Boone dead. It\'s odd for a horror film to be this well done.The problems with the movie...well there are a few, but the positives outweigh the negatives. The script features the occasional lame jokes to try and add some humor, but almost every one falls flat. The mutant creatures look great and for the most part are well acted, but sometimes it feels like they are just posing their awesome makeup for the camera. The worst part of the film would have to be the climax. It takes so long, and is just constant chaos. It\'s the portion of the film that moves from individual characters and nice tight knit shots, to fiery explosions from each direction and violence happening to characters we don\'t know or care about.Overall, this movie is amazing to look at. It\'s a well done horror film, but even with that said, it has the occasional failure in character\'s lines, and a messy climax. Nonetheless, this is one to check out.My rating: *** out of ****. 101 mins. R for strong violence and language.'

In [11]:
# function to clean the review text by removing HTML tags 
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [12]:
df['review'] = df['review'].apply(clean_html)

In [13]:
# conver lower case
def convert_lower(text):
    return text.lower()

In [14]:
df['review'] = df['review'].apply(convert_lower)

In [15]:
# function to remove special characters from the review text using Regular Expressions (regex). The regex pattern '[^a-zA-Z0-9\s]' matches any character that is not a letter (uppercase or lowercase), a digit, or whitespace. This effectively captures special characters, which can then be removed from the text.
def remove_special_characters(text):
    x=''
    for i in text:
        if i.isalnum() or i.isspace():
            x+=i
        else:
            x+=' '

    return x

In [16]:
df['review'] = df['review'].apply(remove_special_characters)

In [17]:
# remove stop words from the review text using the Natural Language Toolkit (nltk). Stop words are common words that are often removed from text data to improve the performance of natural language processing models. The function takes a string of text as input, splits it into individual words, filters out any stop words, and then joins the remaining words back into a single string.
import nltk
from nltk.corpus import stopwords
def remove_stop_words(text):
    x=[]
    for i in text.split():
        if i in stopwords.words('english'):
            x.append(i)

    y=x[:]
    x.clear()
    return y

In [18]:
df['review'] = df['review'].apply(remove_special_characters)

In [19]:
df["review"] = df["review"].str.split()
df["review"].iloc[0]

['the',
 '60s',
 '1999',
 'd',
 'mark',
 'piznarski',
 'josh',
 'hamilton',
 'julia',
 'stiles',
 'jerry',
 'o',
 'connell',
 'jeremy',
 'sisto',
 'jordana',
 'brewster',
 'leonard',
 'roberts',
 'bill',
 'smitrovich',
 'annie',
 'corley',
 'charles',
 's',
 'dutton',
 'nbc',
 'mini',
 'series',
 'later',
 'released',
 'to',
 'video',
 'dvd',
 'as',
 'full',
 'length',
 'feature',
 'film',
 'about',
 'the',
 'treacherous',
 '1960s',
 'as',
 'seen',
 'through',
 'the',
 'eyes',
 'of',
 'both',
 'a',
 'white',
 'family',
 'and',
 'a',
 'black',
 'family',
 'the',
 'film',
 's',
 'first',
 'half',
 'is',
 'driven',
 'by',
 'the',
 'excellent',
 'performance',
 'of',
 'dutton',
 'as',
 'reverend',
 'willie',
 'taylor',
 'and',
 'evenly',
 'spreads',
 'the',
 'storyline',
 'between',
 'the',
 'families',
 'however',
 'dutton',
 's',
 'character',
 'is',
 'killed',
 'halfway',
 'through',
 'and',
 'the',
 'black',
 'family',
 'is',
 'completely',
 'forgotten',
 'in',
 'a',
 'dull',
 'incoherent',
 'and',
 'downright',
 'awful',
 '2nd',
 'half',
 'rating',
 '4',
 'out',
 'of',
 '10',
 'not',
 'rated',
 'later',
 'rated',
 'pg',
 '13',
 'for',
 'video',
 'dvd',
 'release']

In [20]:
df.head()

                                                  review  sentiment
21925  [the, 60s, 1999, d, mark, piznarski, josh, ham...          0
41703  [this, sleek, sexy, movie, is, a, must, see, o...          0
41531  [if, you, re, looking, for, an, original, horr...          1
32676  [okul, is, the, first, of, its, kind, in, turk...          1
45498  [sur, mes, lèvres, or, read, my, lips, is, fin...          1

In [21]:
# Performing sentiment analysis on the cleaned review text using the TextBlob library. The function takes a string of text as input, creates a TextBlob object, and then calculates the sentiment polarity of the text. The polarity score ranges from -1 (negative sentiment) to 1 (positive sentiment), with 0 indicating neutral sentiment. The function returns the polarity score as a float.
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [22]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z= y[:]
    y.clear()
    return z

In [23]:
stem_words(["I","loved", "loving","it"])

['i', 'love', 'love', 'it']

In [24]:
df['review'] = df['review'].apply(stem_words)

In [25]:
# join back
def join_back(text):
    return ' '.join(text)

In [26]:
df['review'] = df['review'].apply(join_back)

In [27]:
df.review.head()

21925    the 60 1999 d mark piznarski josh hamilton jul...
41703    thi sleek sexi movi is a must see onli upon mu...
41531    if you re look for an origin horror flick thi ...
32676    okul is the first of it kind in turkish cinema...
45498    sur me lèvre or read my lip is fine littl thri...
Name: review, dtype: object

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [29]:
X=cv.fit_transform(df['review']).toarray()

In [30]:
X.shape

(10000, 36458)

In [31]:
y = df.iloc[:, -1].values

In [32]:
y.shape

(10000,)

In [33]:
y

array([0, 0, 1, ..., 0, 1, 0])

In [34]:
# Split the dataset into training and testing sets using sklearn's train_test_split function.
# The test size is set to 20% of the dataset, and a random state is provided for reproducibility.
from sklearn.model_selection import train_test_split

In [35]:
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [36]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 36458), (2000, 36458), (8000,), (2000,))

In [37]:
from sklearn.naive_bayes import GaussianNB ,MultinomialNB, BernoulliNB

In [38]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [39]:
clf1.fit(X_train , y_train)

GaussianNB()

In [40]:
clf2.fit(X_train , y_train)

MultinomialNB()

In [41]:
clf3.fit(X_train , y_train)

BernoulliNB()

In [42]:
y_pred1 = clf1.predict(X_test)

In [43]:
y_pred2 = clf2.predict(X_test)

In [44]:
y_pred3 = clf3.predict(X_test)

In [45]:
y_test.shape

(2000,)

In [46]:
y_pred1.shape

(2000,)

In [47]:
from sklearn.metrics import accuracy_score

In [48]:
print("Gaussion",accuracy_score(y_test , y_pred1))

Gaussion 0.634

In [49]:
print("Multinomial",accuracy_score(y_test , y_pred2))

Multinomial 0.839

In [50]:
print("Bernolli",accuracy_score(y_test , y_pred3))

Bernolli 0.843